apiVersion: replication.postgresql.upbound.io/v1alpha1
kind: Slot
metadata:
  annotations:
    meta.upbound.io/example-id: replication/v1alpha1/slot
  labels:
    testing.upbound.io/example-name: my_slot
  name: my-slot
spec:
  forProvider:
    name: my_slot
    plugin: test_decoding
